server:
  port: 10100
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.74.130:8848
        username: nacos
        password: nacos
        namespace: 311853ea-26c0-46e5-83e9-5d5923e1a333

    gateway:
      routes:
        - id: "gateway-test"
          uri: "http://www.bilibili.com"
          predicates:
            - Path=/bilibili




        - id: coupon-route
          uri: lb://mall-coupon
          predicates:
            - Path= /api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: member-route
          uri: lb://mall-member
          predicates:
            - Path= /api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: order-route
          uri: lb://mall-order
          predicates:
            - Path= /api/order/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: product-route
          uri: lb://mall-product
          predicates:
            - Path= /api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: ware-route
          uri: lb://localhost:9900
          predicates:
            - Path= /api/ware/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}



        - id: oss-policy
          uri: http://localhost:10200
          predicates:
            - Path= /api/thirdparty/oss/policy
          filters:
            - RewritePath= /api/(?<segment>/?.*),/$\{segment}

        - id: admin-route
          uri: lb://mall-Admin
          predicates:
            - Path= /api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}


        - id: host-route
          uri: lb://mall-product
          predicates:
            - Host=**.katzenyasax-mall














  main:
    web-application-type: reactive
  application:
    name: mall-Gateway











