server:
  port: 10100
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.74.128:8848
        username: nacos
        password: nacos
        namespace: 311853ea-26c0-46e5-83e9-5d5923e1a333

    gateway:
      routes:
        - id: "gateway-test"
          uri: "http://www.bilibili.com"
          predicates:
            - Path=/bilibili






        - id: product-route
          uri: http://localhost:8800
          predicates:
            - Path= /api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: admin-route
          uri: http://localhost:8080
          predicates:
            - Path= /api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/renren-fast/$\{segment}
















  main:
    web-application-type: reactive
  application:
    name: mall-Gateway











