spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.74.130:8848
        username: nacos
        password: nacos
        namespace: 311853ea-26c0-46e5-83e9-5d5923e1a333


  application:
    name: mall-cart
  thymeleaf:
    cache: false

  data:
    redis:
      host: 192.168.74.130
      port: 6379


server:
  port: 10500





mall:
  thread:
    core-size:  20
    max-size: 200
    keep-alive-time:  10




