spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.74.130:3306/mall_pms
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.74.130:8848
        password: nacos
        username: nacos
        namespace: 311853ea-26c0-46e5-83e9-5d5923e1a333

  application:
    name: mall-product
  thymeleaf:
    cache: false




mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      #不删除
      logic-not-delete-value: 1
      #删除


server:
  port: 8800



logging:
  level:
    com.katzenyasax.mall: debug












